markdown: redcarpet
baseurl: /GamespawnRedesignV2
exclude: ['README.md', 'LICENSE']

collections:
  projects:
    output: true

defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: project_page
      extra_css: project_page.css